version: '3'
services:
  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_DEV=true
    ports:
      - 2113:2113
      - 1113:1113